default:
  online_dates: "June 8 - June 18, 2026"
  online_times: "10:30am - 2pm Pacific Time"
  codeathon_dates: "June 29 - July 1, 2026"
  codeathon_times: "9:30am - 4pm Pacific Time"
  register_link: "https://forms.gle/oaCfASYazKqKvx2V8"
  codeathon_schedule: "https://docs.google.com/document/d/1ZD-w0vc3Vtv1vf95h6323zaaxORg9vC7Hp4I_IUeW0I/edit?usp=sharing"
  instructor_slides: "https://drive.google.com/drive/folders/18LZlTF-iGwM6kZvFGeoFq1wFmIvOyCYQ?usp=sharing"
  lightning_talk_folder: ""

  pulsecheck_survey: "https://forms.gle/3AAf2WstqVsuiM8V7"
  research_survey: "https://forms.gle/t8yEYJYh7BuXtnFB7"
  
  slack_workspace: "https://daseh.slack.com/"
  instructors: "[Carrie Wright](https://carriewright11.github.io/), [Ava Hoffman](https://www.avahoffman.com/), [Elizabeth Humphries]()"
  r_version: "(4.6.0 (called 'Because it was There') as of April 24, 2026)"
  r_dl_mac_m1: "https://cran.r-project.org/bin/macosx/sonoma-arm64/base/R-4.6.0-arm64.pkg"
  r_dl_mac_intel: "https://cran.r-project.org/bin/macosx/big-sur-x86_64/base/R-4.6.0-x86_64.pkg"
  r_dl_windows: "https://cran.r-project.org/bin/windows/base/R-4.6.0-win.exe"
  rstudio_dl_mac: "https://download1.rstudio.org/electron/macos/RStudio-2026.04.0-526.dmg"
  rstudio_dl_windows: "https://download1.rstudio.org/electron/windows/RStudio-2026.04.0-526.exe"
