
<div class="leaf"></div> 
# Materials + Schedule
***


It's helpful to [install software](modules/Setup/Setup.html) before you start DaSEH. We also recommend completing HW 1 (Swirl module indicated below) before class so we can hit the ground running!

<br>


## Online Overview

| Time (PT)           | Content   |
|---------------------|-----------|
| 10:30am - 11:30am   | Session 1 |
| 11:30am - 11:40am   | Break     |
| 11:40am - 12:40pm   | Session 2 |
| 12:40pm - 12:50pm   | Break     |
| 12:50pm - 2:00pm    | Session 3 |

*Note: Timing is approximate*

<br>

## Online Schedule + Materials

```{r, results='asis', echo = FALSE, message=FALSE, warning = FALSE}
# The str_replace_all creates an absolute url to linked documents since there are word and pdf rendered versions of the syllabus
source("scripts/utils.R")
pander::pandoc.table(
  read_markdown("docs/_schedule_table.Rmd") %>%
    mutate(across(
      .fns = ~ str_replace_all(., "\\./", "https://daseh.org/")
    )),
  missing = "",
  split.tables = Inf,
  style = "rmarkdown"
)
```

<br>

## In-person Code-a-thon Schedule + Materials

- [Schedule](`r config::get("codeathon_schedule")`)
- [Instructor Slides](`r config::get("instructor_slides")`)
- [Lightning Talk Upload Folder](`r config::get("lightning_talk_folder")`)
- [Project Template](modules/Project_Template/Project_Template.Rmd)
- [Project Example](modules/Project_Example/Project_Example.Rmd)
- [Project Example (rendered)](modules/Project_Example/Project_Example.html)

<br>
